language: perl
sudo: false
addons:
  apt:
    packages:
    - libgsl0-dev
    - gnuplot
install:
- export FL_PREFIX=~/local
- make libbuild
- make libinstall
- cpanm PDL PDL::Graphics::Gnuplot
script:
- export PL_PREFIX=~/local
- make pdlbuild
- pushd pdl && make test && popd
